# Generated by Django 4.2.7 on 2025-06-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
    ]
