# Generated by Django 4.2.7 on 2025-06-11 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20250610_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subscription_expires", models.DateTimeField(blank=True, null=True)),
                ("daily_chats_used", models.PositiveIntegerField(default=0)),
                ("last_chat_reset", models.DateField(auto_now_add=True)),
                ("profile_views", models.PositiveIntegerField(default=0)),
                ("can_see_profile_views", models.BooleanField(default=False)),
                ("can_hide_ads", models.BooleanField(default=False)),
                ("extended_discovery_radius", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
