# Generated by Django 4.2.7 on 2025-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_chats_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="max_daily_chats",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("business", "Business"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
