# Generated by Django 4.2.7 on 2025-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_daily_chats_used_user_max_daily_chats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
