version: '3.8'

services:
  # Django Application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-local-secret-key-change-this
      - DATABASE_URL=postgresql://postgres:password@db:5432/walking_buddy
      - REDIS_URL=redis://redis:6379
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn django_walking_buddy.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --reload"

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=walking_buddy
      - POSTGRES_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for Channels/Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Celery Worker (optional)
  celery:
    build: .
    command: celery -A django_walking_buddy worker -l info
    environment:
      - DEBUG=True
      - SECRET_KEY=your-local-secret-key-change-this
      - DATABASE_URL=postgresql://postgres:password@db:5432/walking_buddy
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  # Celery Beat (optional)
  celery-beat:
    build: .
    command: celery -A django_walking_buddy beat -l info
    environment:
      - DEBUG=True
      - SECRET_KEY=your-local-secret-key-change-this
      - DATABASE_URL=postgresql://postgres:password@db:5432/walking_buddy
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: