# Generated by Django 4.2.7 on 2025-06-10 20:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('pace', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('weather_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('weather_humidity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'walks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='walk_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_photos', to=settings.AUTH_USER_MODEL)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='walks.walk')),
            ],
            options={
                'db_table': 'walk_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_messages', to=settings.AUTH_USER_MODEL)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='walks.walk')),
            ],
            options={
                'db_table': 'walk_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks_participated', to=settings.AUTH_USER_MODEL)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='walks.walk')),
            ],
            options={
                'db_table': 'walk_participants',
                'unique_together': {('walk', 'user')},
            },
        ),
    ]
