# Generated by Django 4.2.7 on 2025-06-11 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ad_campaigns",
            },
        ),
        migrations.CreateModel(
            name="AdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("impression", "Impression"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("chat", "Chat"),
                            ("profile", "Profile"),
                            ("sidebar", "Sidebar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ad_id", models.CharField(max_length=100)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ad_events",
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="ad_events_event_t_0bf8b3_idx",
                    ),
                    models.Index(
                        fields=["placement", "created_at"],
                        name="ad_events_placeme_6bb7eb_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ad_events_user_id_c9a8b1_idx",
                    ),
                ],
            },
        ),
    ]
